export const modalConfigs = {
  small: { width: "max-w-md" },
  medium: { width: "max-w-lg" },
  large: { width: "max-w-2xl" },
  delete: {
    title: "삭제 확인",
    description: "정말로 삭제하시겠습니까?",
    warning: null,
    icon: "trash",
    iconColor: "text-red-500",
    iconSize: 32,
    buttonCancelText: "취소",
    buttonConfirmText: "삭제",
    buttonDisabled: false,
    info: null,
  },
  success: {
    title: "성공",
    description: "작업이 완료되었습니다.",
    icon: "circleCheck",
    iconColor: "text-green-500",
    iconSize: 32,
    buttonConfirmText: "확인",
    buttonDisabled: false,
    info: null,
  },
  deleteSuccess: {
    title: "삭제 완료",
    description: "선택한 항목이 삭제되었습니다.",
    icon: "circleCheck",
    iconColor: "text-green-500",
    iconSize: 32,
    buttonConfirmText: "확인",
    buttonDisabled: false,
    info: "복원이 필요한 경우 관리자에게 문의해주세요.",
    infoColor: "text-blue-600 dark:text-blue-400",
  },
  error: {
    title: "오류 발생",
    description: "문제가 발생했습니다.",
    icon: "exclamationTriangle",
    iconColor: "text-red-500",
    iconSize: 32,
    buttonConfirmText: "확인",
    buttonDisabled: false,
    info: null,
  },
  progress: {
    title: "처리 중...",
    description: "잠시만 기다려주세요.",
    icon: "loading",
    iconColor: "text-blue-500",
    iconSize: 32,
    buttonDisabled: true,
    info: null,
  },
} as const;
